apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-staging
  template:
    metadata:
      labels:
        app: redis-staging
    spec:
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379
