apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-prod
spec:
  replicas: 5
  selector:
    matchLabels:
      app: redis-prod
  template:
    metadata:
      labels:
        app: redis-prod
    spec:
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379
